# Generated by Django 3.2 on 2023-01-30 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='create_uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='r_object',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='update_uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='create_uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='r_object',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
