# Generated by Django 3.2 on 2023-02-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230212_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='r_object',
            field=models.JSONField(default={'commits': [{'campos_mutated': [], 'comment': 'Nuevo elemento creado', 'date': '2020-01-01 00:00:00', 'fecha': 'miércoles, 1 enero 2020 00:00', 'nombre_usuario': '?', 'type': 'new', 'user_icon': 'null', 'user_id': '?'}]}, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='r_object',
            field=models.JSONField(default={'commits': [{'campos_mutated': [], 'comment': 'Nuevo elemento creado', 'date': '2020-01-01 00:00:00', 'fecha': 'miércoles, 1 enero 2020 00:00', 'nombre_usuario': '?', 'type': 'new', 'user_icon': 'null', 'user_id': '?'}]}, null=True),
        ),
    ]
